title: My first github page with jekyll
author: Iulia Micut
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Github pages with jekyll seems interesting even if is am not sure for what it would be usefull.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
